export type ThemeColors = {
  text: string
  subText: string
  textInverse: string
  brandLight: string
  brandMedium: string
  brandDark: string
  brandAccentColor: string
  bodyBackground: string
  bodyBackgroundDark: string
  navbarBackground: string
  navbarBackgroundScrolled: string
  navbarBorder: string
  linkColor: string
  linkHoverColor: string
  boxShadow: string
  toggleColor: string
  toggleColorActive: string
  buttonColor: string
  buttonColorActive: string
  footerText: string
  footerHeading: string
  Grey1: string
  Grey2: string
  Grey3: string
  Grey4: string
  Grey5: string
  Grey6: string
  Grey7: string
  Grey8: string
  Grey9: string
  Grey10: string
  Grey11: string
  Grey12: string
  Grey13: string
  Grey14: string
  disabledColour: string
  danger: string
  warning: string
  info: string
  white: string
  black: string
}
