name: Build & Test on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stuart-hopwood-cv
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build    
